name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      BRIDGE_HOSTNAME: ${{ secrets.BRIDGE_HOSTNAME }}
      PRODUCTION_HOSTNAME: ${{ secrets.PRODUCTION_HOSTNAME }}
      DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      VITE_GITHUB_CALLBACK_URL: ${{ secrets.GITHUB_CALLBACK_URL }}
      VITE_GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      VITE_ACCESS_API_URL: ${{ secrets.ACCESS_API_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Build project
        run: pnpm build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host unison-bridge\n\tHostName $BRIDGE_HOSTNAME\n\tUser $DEPLOY_USERNAME\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tForwardAgent yes\n" > ~/.ssh/config
          echo -e "Host unison-production\n\tHostName $PRODUCTION_HOSTNAME\n\tUser $DEPLOY_USERNAME\n\tProxyJump unison-bridge\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tForwardAgent yes\n" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Transfer files to Production
        run: |
          rsync -rvz --delete --exclude=".git" --exclude="node_modules" ./ unison-production:/var/www/access.csipro.isi.unison.mx/

      - name: SSH to Production and install dependencies
        run: ssh unison-production "cd /var/www/access.csipro.isi.unison.mx && rm -rf node_modules && ~/.local/share/pnpm/pnpm --prod install"

